name: Build APK

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install system dependencies
      run: |
        sudo apt update
        sudo apt install -y \
          build-essential \
          ccache \
          git \
          libffi-dev \
          libssl-dev \
          libsqlite3-dev \
          libjpeg-dev \
          libfreetype6-dev \
          zlib1g-dev \
          pkg-config \
          unzip \
          openjdk-17-jdk \
          python3-pip \
          libpng-dev \
          liblzma-dev \
          libtool \
          automake \
          libgl1-mesa-dev \
          libgles2-mesa-dev

    - name: Install Python & Buildozer dependencies
      run: |
        pip install --upgrade pip
        pip install cython
        pip install "buildozer[android]"

    - name: Set up Android SDK (build-tools, platforms, etc.)
      run: |
        yes | buildozer android update

    - name: Build APK
      run: buildozer android debug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: app-debug.apk
        path: bin/*.apk
