name: Build APK

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install system dependencies
      run: |
        sudo apt update
        sudo apt install -y \
          build-essential \
          ccache \
          git \
          libffi-dev \
          libssl-dev \
          libsqlite3-dev \
          libjpeg-dev \
          libfreetype6-dev \
          zlib1g-dev \
          pkg-config \
          unzip \
          openjdk-17-jdk \
          python3-pip \
          libpng-dev \
          liblzma-dev \
          libtool \
          automake \
          libgl1-mesa-dev \
          libgles2-mesa-dev

    - name: Install Buildozer with Android support
      run: |
        pip install --upgrade pip
        pip install "buildozer[android]"

    # DO NOT clean before python-for-android exists!
    # - name: Clean previous builds
    #   run: buildozer android clean

    - name: Build APK
      run: buildozer android debug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: app-debug.apk
        path: bin/*.apk
