name: Build APK

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build Android APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Upgrade pip and install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --user buildozer cython virtualenv

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Android SDK
        run: |
          mkdir -p $HOME/android-sdk/cmdline-tools
          cd $HOME/android-sdk/cmdline-tools
          curl -o sdk.zip https://dl.google.com/android/repository/commandlinetools-linux-10406996_latest.zip
          unzip -q sdk.zip -d temp
          mv temp/cmdline-tools latest
          yes | $HOME/android-sdk/cmdline-tools/latest/bin/sdkmanager --sdk_root=$HOME/android-sdk \
            "platform-tools" \
            "platforms;android-33" \
            "build-tools;33.0.2" \
            "ndk;25.2.9519653" \
            "cmake;3.22.1"

      - name: Set environment variables
        run: |
          echo "ANDROIDSDK=$HOME/android-sdk" >> $GITHUB_ENV
          echo "ANDROIDNDK=$HOME/android-sdk/ndk/25.2.9519653" >> $GITHUB_ENV
          echo "ANDROIDAPI=33" >> $GITHUB_ENV
          echo "ANDROIDMINAPI=21" >> $GITHUB_ENV

      - name: Initialize Buildozer
        run: buildozer init

      - name: Update buildozer.spec
        run: |
          sed -i 's/^# *log_level = .*/log_level = 2/' buildozer.spec
          sed -i 's/^# *android.permissions = .*/android.permissions = INTERNET/' buildozer.spec
          sed -i 's/^# *android.api = .*/android.api = 33/' buildozer.spec
          sed -i 's/^# *android.ndk = .*/android.ndk = 25.2.9519653/' buildozer.spec
          sed -i 's/^# *android.ndk_path = .*/android.ndk_path = $HOME\/android-sdk\/ndk\/25.2.9519653/' buildozer.spec
          sed -i 's/^# *android.sdk_path = .*/android.sdk_path = $HOME\/android-sdk/' buildozer.spec
          sed -i 's/^# *requirements = .*/requirements = python3,kivy,flask,numpy,requests,face_recognition,Pillow/' buildozer.spec
          sed -i 's/^# *arch = .*/arch = arm64-v8a,armeabi-v7a/' buildozer.spec
          sed -i 's/^# *android.ndk_api = .*/android.ndk_api = 21/' buildozer.spec
          sed -i 's/^# *android.build_tools_version = .*/android.build_tools_version = 33.0.2/' buildozer.spec

      - name: Build APK
        run: buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: faceappattendance-debug-apk
          path: bin/*.apk
