name: Build APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            zip unzip openjdk-17-jdk \
            python3-pip libffi-dev libssl-dev \
            libxml2-dev libxslt1-dev zlib1g-dev \
            libsqlite3-dev libjpeg-dev \
            libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-ttf-dev \
            libportmidi-dev libswscale-dev libavformat-dev libavcodec-dev \
            libfreetype6-dev libgl1-mesa-dev libgles2-mesa-dev \
            libmtdev-dev \
            build-essential autoconf libtool pkg-config \
            git python3-setuptools

      - name: Install Cython and Buildozer
        run: |
          pip install --upgrade pip Cython==0.29.36
          pip install buildozer

      - name: Create .buildozer folder if missing
        run: |
          mkdir -p .buildozer

      - name: Build APK with Buildozer
        run: |
          buildozer android debug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: faceappattendance-debug.apk
          path: bin/*.apk
