name: Build APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Upgrade pip and install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            ccache \
            libncurses5-dev \
            libstdc++6 \
            libffi-dev \
            libssl-dev \
            libsqlite3-dev \
            zlib1g-dev \
            libjpeg-dev \
            libfreetype6-dev \
            libpng-dev \
            libavcodec-dev \
            libavformat-dev \
            libswscale-dev \
            libx11-dev \
            libglib2.0-dev \
            libbz2-dev \
            liblzma-dev \
            openjdk-11-jdk \
            unzip \
            git \
            libunwind-dev
          python3 -m pip install --upgrade pip setuptools wheel cython virtualenv

      - name: Install Buildozer
        run: |
          pip install --upgrade buildozer

      - name: Install Android SDK command line tools
        run: |
          mkdir -p "$HOME/android-sdk"
          cd "$HOME/android-sdk"
          curl -o cmdline.zip https://dl.google.com/android/repository/commandlinetools-linux-10406996_latest.zip
          mkdir -p cmdline-tools
          unzip -q cmdline.zip -d cmdline-tools/temp
          mv cmdline-tools/temp/cmdline-tools cmdline-tools/latest
          yes | cmdline-tools/latest/bin/sdkmanager --sdk_root=$HOME/android-sdk \
            "platform-tools" \
            "platforms;android-33" \
            "build-tools;33.0.2" \
            "ndk;25.2.9519653"

      - name: Set environment variables
        run: |
          echo "ANDROIDSDK=$HOME/android-sdk" >> $GITHUB_ENV
          echo "ANDROIDNDK=$HOME/android-sdk/ndk/25.2.9519653" >> $GITHUB_ENV
          echo "ANDROIDAPI=33" >> $GITHUB_ENV
          echo "ANDROIDMINAPI=21" >> $GITHUB_ENV

      - name: Build APK with Buildozer
        run: |
          buildozer android clean
          buildozer -v android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: faceapp-debug-apk
          path: bin/*.apk
